### ISSUE TITLE
Confirgure SSL

### ISSUE THREAD

**Issue by jonathanloos** [jonathanloos/volley-stats#65]
Generate and host a custom SSL certificate: https://letsencrypt.org/getting-started/

**Comment by jonathanloos** [comment]
For tracking, here are some helpful links for getting things setup:
1. Example implementation: https://guillaumebriday.fr/how-to-deploy-rails-with-kamal-and-ssl-certificate-on-vps
2. Traefik setup at basecamp: https://github.com/basecamp/kamal/discussions/112
3. SSL Server Test: https://www.ssllabs.com/ssltest/index.html

**Comment by jonathanloos** [comment]
And it's working!!!

### Granting access for Traefik to write certs
I hadn't run the following command to create/grant access for Traefik to generate the certificates.
```bash
mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json
```

I went into the VM and checked to find that :
```bash
cat /letsencrypt/acme.json
```
returned that it was a directory (wrong!). After removing the directory and re-generating it with the above command, `kamal reboot traefik` did the trick.

### Container Name
Not sure if this is obvious, but in the `config/deploy.yml` there is a `labels` section for servers which needs to point to your container name:

```yml
servers:
  web:
    hosts:
      - x.x.x.x
    labels:
      traefik.http.routers.your_container_name.rule: Host(`example.com`)
      traefik.http.routers.your_container_name_secure.entrypoints: websecure
      traefik.http.routers.your_container_name_secure.rule: Host(example.com`)
      traefik.http.routers.your_container_name_secure.tls: true
      traefik.http.routers.your_container_name_secure.tls.certresolver: letsencrypt
```
